### ISSUE TITLE
Failed to load VB-CNN model!

### ISSUE THREAD

**Issue by HonestDeng** [ICL-ml4csec/VulBERTa#2]
When I tried to load the fine-tuned model VB-CNN-draper using _torch.load('models/VB-CNN_draper/archive/data.pkl')_, there was an error:
_UnpicklingError: A load persistent id instruction was encountered, but no persistent_load function was specified._
Someone in stackoverflow said that uncompatible torch version was the reason. But my _torch.__version__ == '1.7.0+cu110'_. It satisfies the requirement in the README.txt.
Someone can help me? Thanks!

**Comment by hazimfrodo** [comment]
Hi.

Sorry for the very late response. Missed it
Are you sure you are loading the right file?
I checked, and currently, there is no such file `archive/data.pkl` in the `models/VB-CNN_draper` directory.

The model directory for VB-CNN-draper is:
`finetuning_models/VB-CNN_draper/model_ep_15.tar`

Thanks
